### ISSUE TITLE
Cadence Tutorials - Marketplace

### ISSUE THREAD

**Issue by psiemens** [onflow/flow#362]
Marketplace tutorial was fixed so that there are no longer bugs in the contracts or transactions, but more fundamental work needs to be done.

* Update the Fungible token to `ExampleToken` from the first tutorial.
* Update the NFT to `ExampleNFT` from the NFT tutorial.
* Use something similar to the Kitty Items marketplace contract to encourage Cadence best practices

**Comment by joshuahannan** [comment]
I reopened this because I wasn't able to get to making all the improvements I wanted from the other ticket. I'm moving hthis back to the backlog and putting it into a later sprint

**Comment by 0xAlchemist** [comment]
@joshuahannan @robmyers I have some free time next week if you'd like an extra pair of hands for this type of stuff

**Comment by joshuahannan** [comment]
@0xAlchemist We'd love the help! As the description says, we'd like to update the marketplace tutorial to have something similar to the kitty items marketplace smart contract, because that is a more sophisticated version of a marketplace that we want to share with developers. Updating the tutorial would definitely be a bit of an undertaking, but if you think you're up for it, I'd love to get on a call and talk about the plans!

**Comment by 0xAlchemist** [comment]
@joshuahannan no problem, I'd be happy to help - I'll reach out on Discord to setup a call!

**Comment by joshuahannan** [comment]
@robmyers Eric wants to help update the marketplace tutorial and we think that we'd like to do it for a contract like the kitty items marketplace contract. We just have a few things we'd like to confirm before we start. 

Do you feel pretty good about what is currently [in the kitty items repo?](https://github.com/onflow/kitty-items/blob/master/cadence/contracts/KittyItemsMarket.cdc) We'll start working off of that if you're good with it. (might make a PR to the kitty items repo with some changes if needed)
Do you have more docs anywhere about the kitty items contracts?

**Comment by robmyers** [comment]
The marketplace in kittyitems is meant to be being replaced by the storefront in -

https://github.com/onflow/kitty-items/tree/rm/storefront/kitty-items-cadence/cadence/nftStorefront

But that is a little more complex and less regular than the kitty-items marketplace, which was a sketch for it. So as an introductory piece of code it might be better to stick with the marketplace.

There are some notes in Notion but I don't think they're particularly useful, mack has produced thekitty-items documentation so it's worth asking him about it.

I can answer any questions otherwise. 😺
