### ISSUE TITLE
Network status page/widget

### ISSUE THREAD

**Issue by psiemens** [onflow/flow#406]
### Issue To Be Solved

Flow users currently do not have a source of truth for the current network status. We should provide the following:

- Current status of Testnet & Mainnet (healthy, degraded, unavailable)
- Latest bulletin messages from node operation team

### (Optional): Suggest A Solution

TODO: add suggested solution

### (Optional): Context

This is an action item from the communication & release retro.

**Comment by psiemens** [comment]
May be able to use the service that @orodio has already built

**Comment by 10thfloor** [comment]
> May be able to use the service that @orodio has already built

I added a widget, which also links to Jame's more detailed 'flow-view-source/status' page.

**Comment by srinjoyc** [comment]
I'd recommend doing a separate subdomain (status.onflow.org) for the status page and adding a very prominent link to it from the main onflow.org site.

On this page, we should display the status of main net and test net (with the statuses Peter suggested) along with all spork information coming from the comms repo. There is currently no persistent way of viewing all the spork info and updates in one page (they are just delivered over discord). Since files are already formatted and we have integrations set up, this could potentially just be setting up another github action or so. I believe we also use comms to notify of breaking changes to any of the products/repos as well so this information would be quite valuable to capture in one place and direct people to.

Ideally this page would be the goto for any active developer to check for all pertinent information to their development.

**Comment by kerrywei** [comment]
this can be closed given we now have a status page at https://docs.onflow.org/status/ . it tells statuses of mainnet, testnet, and canarynet + spork information.
