### ISSUE TITLE
Use Zip for archives

### ISSUE THREAD

**Issue by bluesign** [onflow/flow#870]
First of all thank you very much for the addition of `protocolDBArchive` and `executionStateArchive` in sporks.json.

One minor problem I have is the `tar.gz` format unfortunately, is it possible to replace it with `zip` ?

Currently I have to download the archive and have to extract before use ( limitation of tar.gz ) but if it was Zip I would be able to use without extracting with VFS. 

Files are little too big for my limited setup, latest sporks are giving me a lot of hard time :(

**Comment by bluesign** [comment]
Is there any chance to implement this? or should I close the issue ?

**Comment by SaveTheRbtz** [comment]
Sorry to randomly jump into the discussion, looking at the [zipfs](https://pkg.go.dev/golang.org/x/tools@v0.1.10/godoc/vfs/zipfs) it may only be useful for tiny use-cases since it does not truly support [io.Seeker](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.10:godoc/vfs/zipfs/zipfs.go;l=173).  You can likely try that for yourself by adding an additional step in your download pipeline by converting the `tar.gz` archive into `zip`.  Since both formats use streaming compression and decompression it can be done without dumping it on the filesystem in the meantime.

PS. You can try re-compressing the archive on the fly into a "seekable" compressed format, e.g. w/ https://github.com/SaveTheRbtz/zstd-seekable-format-go but that will require some work to create a `tar.zst` wrapper for the go's VFS.

**Comment by pgebheim** [comment]
Does it need to be seekable?

I think we just need to be able to stream the events in order?

**Comment by bluesign** [comment]
Thanks @SaveTheRbtz for the great ideas.

My thinking was the use zip to optimize for retrieval by file without indexing ( actually I can also index tar.gz in first pass then extract files accordingly )

Using zip also can allow for requesting file on demand:  for example `executionStateArchive` includes checkpoint files which are huge and unnecessary, but you need to download them anyway with tar.gz.  

zipfs can be made seekable probably, by extracting on open to temp and then seek on that file but this [Seekable ZSTD compression](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable_compression_format.md) seems much better choice. 

Not sure about `protocolDBArchive` but I think badger can also utilize zip/zstd. 

I will surely give this recompress on the fly idea a try. Thanks again

**Comment by SaveTheRbtz** [comment]
Good luck there, please ping this ticket or create a new one if you need some help from us!
